### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by RasheedAZ** [flathub/com.ghostery.browser#3]
Thanks for packaging this as flatpak :) I think the browser is open source https://github.com/ghostery/user-agent-desktop but the Flathub page says it's proprietary...?

**Comment by milouse** [comment]
Yes, this browser is available under the terms of the MPL2. The same is said on the flathub page. What makes you think the flathub page says it is proprietary?

**Comment by RasheedAZ** [comment]
Thanks for following up. I could have sworn it said proprietary when I created this issue. It's giving the correct licence now. I've been seeing similar issues across Flathub so much so that I have to manually verify the licence every time. Someone posted a screenshot of another project recently I think Voicegen but now it's fixed. I'm thinking it's a Flahub issue.
